- hosts: all
  module_defaults:
    group/k8s:
      host: "{{host_api_server}}"
      validate_certs: no
  tasks:
   - name: Print the gateway for each host when defined
     ansible.builtin.debug:
       msg: Host api server {{host_api_server}}
   - name: Patch the deployment
     kubernetes.core.k8s_json_patch:
      validate_certs: no
      wait_timeout: 20
      api_key: "{{ apikey }}"
      kind: Deployment
      api_version: apps/v1
      name: cart
      namespace: robot-shop
      patch:
        - op: replace
          path: /spec/template/spec/containers/0/image
          value: "{{image}}"
