- hosts: all
  module_defaults:
    group/k8s:
      host: "{{host_api_server}}"
      validate_certs: no
  tasks:
   - name: Print the gateway for each host when defined
     ansible.builtin.debug:
       msg: Host api server {{host_api_server}} 
   - name: Obtain access token
     k8s_auth:
       host: "{{host_api_server}}"
       validate_certs: no
       username: "{{username}}"
       password: "{{password}}"
     register: k8s_auth_results
   - name: Patch deployment
     kubernetes.core.k8s_json_patch:
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        kind: Deployment
        name: "{{deployment_name}}"
        namespace: "{{namespace}}"
        patch:
          - op: replace
            path: /spec/spec/containers/0/image
            value: robotshop/rs-cart-wrong:latest
