- hosts: all
  module_defaults:
    group/k8s:
      host: "{{host_api_server}}"
      validate_certs: no
  tasks:
   - name: Print the gateway for each host when defined
     ansible.builtin.debug:
       msg: Host api server {{host_api_server}}
   - name: show the status of the pods.
     k8s_info:
      api_key: "{{ apiKey }}"
      api_version: v1
      namespace: "{{namespace}}"
      kind: Pod
      label_selectors:
       - "{{k8s_pod_name}}"
     register: pod_info

   - name: Display pod info
     debug:
      var: pod_info