- hosts: localhost
  gather_facts: no
  collections:
    - community.kubernetes
    - kubernetes.core
  tasks:
   - name: Patch deployment
     kubernetes.core.k8s_json_patch:
      host: https://c109-e.us-east.containers.cloud.ibm.com:32002
      validate_certs: no
      wait_timeout: 20
      api_key: sha256~P7mv0o-Jq_Rb4eg4LdpD4ov-iiUtwzU6P_rg8iRwDiI
      kind: Deployment
      api_version: apps/v1
      name: cart
      namespace: robot-shop
      patch:
        - op: replace
          path: /spec/template/spec/containers/0/image
          value: robotshop/rs-cart:latest